[package]
name = "aethelgard_x"
version = "0.1.0"
edition = "2021"

[dependencies]
cozy-chess = "0.3"
once_cell = "1.18"
# For the future FPGA link
serialport = "4.3" 

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
